name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t fastapi-app .
          docker tag fastapi-app marehone/fastapi-app:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push marehone/fastapi-app:latest

      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Authenticate with Fly.io
        run: echo "${{ secrets.FLY_API_TOKEN }}" | flyctl auth token

      - name: Deploy to Fly.io using Docker Image
        run: flyctl deploy --image marehone/fastapi-app:latest
